name: CI

on:
    push:
        branches: ["main"]
        paths-ignore:
            - "**/README.md"

    pull_request:
        branches: ["main"]
            
jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Node Modules
              run: npm install

            - name: Format Code using Prettier
              run: npm run format

            - name: Run Unit Test coverage
              run: npm run test:coverage

            - name: Upload coverage to CodeCov
              uses: codecov/codecov-action@v2
